### ISSUE TITLE
Erro com Imagem adicional

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/products-feed#1]
Imagem adicional no feed, verificando no GMC, a propriedade de link adicional deve contar apenas uma única imagem, no momento, se há mais de uma adicional estão sendo inseridas separador de vírgula e cada imagem deve estar em uma tad de imagem adicional. Não achei de imagem adicional no facebook.

Exemplo:

```
<g:additional_image_link>
https://ecom-zjoeihfm.sfo2.digitaloceanspaces.com/@v2-1588213549975-camisa-florida-preta-flor-amarela-costas.jpg,https://ecom-zjoeihfm.sfo2.digitaloceanspaces.com/@v2-1588213573026-medidascamisamangacurtakelvys-d.jpg
</g:additional_image_link>
```

**Comment by leomp12** [comment]
Confundi com o examplo para _Text feeds_ na documentação deles

**Comment by leomp12** [comment]
https://github.com/ecomplus/products-feed/commit/d58f5818439cd6d0979fdc5bc06de93bb7fb2513
