### ISSUE TITLE
Erro ao ler xml

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/products-feed#10]
Muitos clientes relataram problemas de leitura do Xml, alguns erros de indisponibilidade de leitura por parte do Google. Em meus testes, tem demorado muito pra carregar o arquivo mesmo os de 500 apenas. Alguns que testei demorou 5 segundos outros 10 segundos. Os de list all precisava carregar primeiro o de 500 para depois pedir para carregar o list all, se não dava erro de working… aumentando a memória resolveria? Digo isso, porque nos que deram erro de working.. ao gerar o código fonte, todos os itens já estavam no xml

**Comment by leomp12** [comment]
"Aquele erro" qual?
Aumentar limite de RAM não altera velocidade, evita outage que daria em erro fatal, se o problema é delay não tem relação com RAM, provavelmente é o proxy controlando.

> Alguns que testei demorou 5 segundos outros 10 segundos

Se você está testando vários em sequência isso tem muita cara de ser o nginx barrando seu IP (e tem que fazer isso mesmo).

**Comment by matheusgnreis** [comment]
Não, testei só de lojas que deram problema. De toda forma, pedi pra particionar xml. No barradoce por exemplo deu dois erros muito estranhos: O arquivo robots.txt do servidor é inacessível e Não é possível resolver o nome do host. Dei allow no google bot, porque já tiveram outros clientes que tiveram esse erro do robots.txt, esse segundo pode ser por conta de apontamentos tipo A para locais distintos, ajustei aqui e esperar propagar. 

Mas o erro de não carregar produtos, deu na customic, disfoil, tecvirtual no dia de ontem e o google falou que era culpa nossa, foi ai quando testei, demorou muito pra carregar, depois que carregou a primeira vez, a segunda foi de boa.

**Comment by leomp12** [comment]
> O arquivo robots.txt do servidor é inacessível

An? Estamos falando do XML aqui ainda? O que tem a ver o XML com robots.txt da loja?

> Não, testei só de lojas que deram problema.

Deixa pelo menos um link de exemplo dos que testou aí.

> depois que carregou a primeira vez, a segunda foi de boa.

A segunda bate cache.

**Comment by matheusgnreis** [comment]
> An? Estamos falando do XML aqui ainda? O que tem a ver o XML com robots.txt da loja?

Sim, erro do gmc:

![image](https://user-images.githubusercontent.com/35343551/192150591-8e91bd96-cf7b-4eaa-a1b5-7b8e06481c44.png)
Falhas na busca do xml:
![image](https://user-images.githubusercontent.com/35343551/192150639-2af9d9f2-0a82-4d5c-9955-11b361be95e6.png)
![image](https://user-images.githubusercontent.com/35343551/192150667-b1802e66-3da3-40f2-9d17-14fc2e607901.png)
Ele 3111 produtos, all estava dando problemas com mais 600 produtos, cerca, ai pedi para trocar de 500 em 500 que deram 7 e 4 hoje de manhã não validaram.

> Deixa pelo menos um link de exemplo dos que testou aí.

https://storefront.e-com.plus/products-feed.xml?store_id=3967&domain=barradoce.com.br

https://storefront.e-com.plus/products-feed.xml?store_id=3041&domain=www.tecvirtual.com.br

**Comment by matheusgnreis** [comment]
Bom dia, hoje de manhã fiz um teste e demorou 1 minuto pra carregar o arquivo, esse primeiro informado:

![image](https://user-images.githubusercontent.com/35343551/192238489-e19f5b84-d64b-4c9d-8961-9c5080f07d4e.png)
Load time 1.2 min. Vou simular algumas coisas no meu local

**Comment by leomp12** [comment]
>  An? Estamos falando do XML aqui ainda? O que tem a ver o XML com robots.txt da loja?

> Sim, erro do gmc:

Tá mas isso não tem nada a ver com o resto da conversa, menos ainda com esse repositório. Tem que ver direito que erro é esse e se necessário mexer algo no robots.txt da loja, não há informação no feed relacionada a robots.txt.

> Load time 1.2 min. Vou simular algumas coisas no meu local

Não tem o que você possa simular em localhost que deixe isso mais rápido.
A o XML com 500 produtos dá muito grande (70kb de JSON é muita coisa) e em média tá finalizando em 70s aqui, o que daria menos de 140ms por produto e uma merreca por item, considerando que tá batendo HTTP em CDN público mesmo, não tem como reduzir drasticamente isso por aqui.
Se esses erros realmente são por tempo máximo da request (o Google não tinha isso antes, a priori acho que não é isso), o melhor a fazer é reduzir os produtos / tabela na verdade, e enviar mais tabelas.
