### ISSUE TITLE
Variações com ausência de especificações

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/products-feed#2]
Nas variações não estão indo as especificações, logo o GMC acusa erro, por exemplo:

![Captura de Tela (112)](https://user-images.githubusercontent.com/35343551/83415893-41d54680-a3f6-11ea-9469-dba61598b653.png)

Não mostra nem gênero, nem Idade e nem cor.

**Comment by matheusgnreis** [comment]
https://storefront.e-com.plus/products-feed.xml?store_id=1035&domain=www.kelvys.com.br&title=ecomplus-gmc.xml

**Comment by leomp12** [comment]
Na verdade o problema é com o `grid_id` e valores das especificações que deveriam ser propriamente parseadas no painel, mesmo assim, adicionei uns parses aqui como fallback https://github.com/ecomplus/products-feed/commit/9bb0e2bd58bea70f75a3227182a13bc8a371a721
