### ISSUE TITLE
mudar atributo colors para color para gmc

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/products-feed#3]
Problema que todas as variações criadas, irão dar problema, porque elas irão começar a renderizar apenas colors na variação. Ou seja, ou alterar aqui, ou altera no product feed, onde tiver colors, mudar para color no feed

**Comment by matheusgnreis** [comment]
https://support.google.com/merchants/answer/6324487?hl=pt-BR

**Comment by leomp12** [comment]
> Problema que todas as variações criadas, irão dar problema, porque elas irão começar a renderizar apenas colors na variação. Ou seja, ou alterar aqui, ou altera no product feed, onde tiver colors, mudar para color no feed

Não entendi o início haha
Mas o problema eu entendi, e a correção é aqui no feed mesmo.
