### ISSUE TITLE
erro no gmc loja adequim

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/products-feed#5]
Loja adequim criou 3 urls para 3 categorias unicas, sem filho. Prmeiro testou pra antimofo

https://storefront.e-com.plus/products-feed.xml?store_id=1143&domain=www.adequim.com.br&title=gmc.xml&search_field=categories.slug&search_value=antimofo&set_properties={“google_product_category_id”:503738}

E ele retorna apenas 5 produtos, sendo que possui 6, além de não setar a google_product_category_id. Não retorna o ADE0008

Depois para impermeabilizante:

https://storefront.e-com.plus/products-feed.xml?store_id=1143&domain=www.adequim.com.br&title=gmcii.xml&search_field=categories.slug&search_value=impermeabilizantes&set_properties={“google_product_category_id”:503738}

Retorna 2 produtos, sendo que possui 3. Falta o ADE0010

Por ultimo a categoria mascaras:

https://storefront.e-com.plus/products-feed.xml?store_id=1143&domain=www.adequim.com.br&title=gmciii.xml&search_field=categories.slug&search_value=mascaras&set_properties={“google_product_category_id”:503724}

Retorna 1 produto, sendo que possui 2. Falta o ADE0011

Se envio todos:

https://storefront.e-com.plus/products-feed.xml?store_id=1143&domain=www.adequim.com.br

Retorna 10 produtos, sendo que possui 11. Falta o ADE0001

**Comment by leomp12** [comment]
@matheusgnreis o `google_product_category_id` porque `{“google_product_category_id”:503738}` é um JSON inválido, “ é diferente de " e o correto seria `{"google_product_category_id":503738}`.

Tô vendo porque tá pulando um produto...

**Comment by matheusgnreis** [comment]
Ah sim, pra mim tinha tentado aqui mudar, mas parece que ficou igual ao dele entao ao invés de " ficou mesmo “

**Comment by leomp12** [comment]
https://github.com/ecomplus/products-feed/commit/a9a607ac9fcec96cbfef41a58dcb215bd4428cda
