### ISSUE TITLE
Incluir todos os produtos no mesmo feed

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/products-feed#7]
Recebi uma notificação de uma agência hoje informando que o Google está aceitando apenas um feed principal de produtos com outros complementares que podem trocar alguma informação em relação ao produto no feed principal. Pesquisei por alto e informa isso, mas não sei se de fato funciona assim ainda. Se funcionar, a maneira como é hoje para acima de 500 produtos não continuará válido

**Comment by leomp12** [comment]
Alguém chegou a ter problemas com isso ou só ouviu falar mesmo? haha
Tem algo em alguma referência oficial do Google ou pelo menos é uma agência de maior porte?

> complementares que podem trocar alguma informação em relação ao produto no feed principal.

Um feed com todos os produtos mas de forma resumida outros feeds com mais informações, é isso?

**Comment by matheusgnreis** [comment]
> Um feed com todos os produtos mas de forma resumida outros feeds com mais informações, é isso?

Isso mesmo. 

> Alguém chegou a ter problemas com isso ou só ouviu falar mesmo? haha

Foi o Centro Fogoes, sugeri ele colocar mais de uma opção pra testar, já que a agência dele lá falou que não podia, ficou de me dar um retorno, mas não deu ainda.

> Tem algo em alguma referência oficial do Google ou pelo menos é uma agência de maior porte?

Conversei com uma agência de grande porte e eles falaram que o google está ficando muito chato, inclusive obrigando a inserção de alguns dados e que mesmo aparecendo lá como aviso, não permite anunciar, um deles, acho que em breve teremos que colocar que é o shipping. Mas isso é cena pro próximo capítulo

**Comment by matheusgnreis** [comment]
A loja em si vai sair, mas conversando com algumas agências, é interessante ter um resumido sem variações, 1 imagem, o mínimo de informações possíveis pra passar e poder conter mais itens.

**Comment by leomp12** [comment]
Não faz diferença na verdade, de qualquer forma tem que fazer todas as requests pra pegar as descrições de todos os produtos. Vou fazer uma opção pro feed mostrar tudo sim, mas aí vai ser com todas as informações logo.
