### ISSUE TITLE
Feed sem produtos 

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/products-feed#8]
Há alguns meses tivemos problema com uma loja que o Google não estava conseguindo manter os produtos com as checagens diárias. Recentemente apareceram duas, que somente com uma checagem manual que resolve (lojista ver que está sem produtos e solicita checagem). Em todos mandei retirar o título, deixando só domínio e store id, as frequências de não aparecer produtos no feed diminuíram, mas esporadicamente acontece

**Comment by leomp12** [comment]
Recentemente quando exatamente? Não coincide com a intermitência da Search
API no dia 22/06? Ou no dia 02/07 atrás o Cloudflare retornando alguns 522
às 06:00 da manhã?

Se não for isso, pra mexer com isso mais rápido eu preciso do XML incorreto
colado aqui, ou pelo menos um link.

Em dom., 4 de jul. de 2021 13:59, Matheus Reis ***@***.***>
escreveu:

**Comment by matheusgnreis** [comment]
Só informou hoje informando que estava com problema, solicitei o XML que ela está inserindo. O outro caso tem 1 mês.

**Comment by leomp12** [comment]
https://github.com/ecomplus/products-feed/commit/a70ad72446c95333b344f9a26ac80109d974daf7
