### ISSUE TITLE
IDs de variação sem SKU

### ISSUE THREAD

**Issue by matheusgnreis** [ecomplus/products-feed#9]
Atualmente, ao gerar o XML, se o produto tem variação, está sendo considerado apenas o sku do body e não das variações em si, no caso gerando erro na importação junto ao facebook, porque informa que existe mais de um produto com o mesmo g:id, um exemplo é:
```
<g:id><![CDATA[ZDZ5252]]></g:id>
<g:title><![CDATA[Vestido Longo - ZDZ5252 / P]]></g:title>
<g:item_group_id><![CDATA[ZDZ5252]]></g:item_group_id>
```

O g:item_group_id deve ser o mesmo na variação, porém o g:id precisa ser diferente.

**Comment by leomp12** [comment]
> Atualmente, ao gerar o XML, se o produto tem variação, está sendo considerado apenas o sku do body e não das variações em si

Não, o objeto $body é um merge da variação (quando existe) com o produto, vão prevalecer os fields da variação inclusive. Se fizesse isso estaria dando erro com todas as variações de todas as lojas desde sempre...

O erro aí é de cadastro, a variação não ter um SKU ou ser igual a do produto, eu até posso evitar pegar o SKU do produto nesse caso e bater o ID da variação, mas isso pode dar erro em diversos outros lugares também.

**Comment by leomp12** [comment]
https://github.com/ecomplus/products-feed/commit/4e1b022a66c260418304ce56ca1c512056431eaa
